#!/usr/bin/env sh

$HOME/.limelight/bin/limelight -m config width 2
$HOME/.limelight/bin/limelight -m config radius 10
#limelight -m config placement exterior
$HOME/.limelight/bin/limelight -m config active_color 0x46D9FFFF
$HOME/.limelight/bin/limelight -m config normal_color 0x282C34FF

echo "limelight configuration loaded.."
